# Generated by Django 4.2.7 on 2024-01-02 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock',
            options={'ordering': ('product',)},
        ),
        migrations.AlterModelOptions(
            name='warehouse',
            options={'ordering': ('name',)},
        ),
    ]
