# Generated by Django 4.2.7 on 2023-12-30 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shirt', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shirt',
            options={'verbose_name': 'Рубашка', 'verbose_name_plural': 'Рубашки'},
        ),
    ]
